services:
  - type: web
    name: system-pakar-app
    runtime: docker  # Diperbaiki: Gunakan Docker untuk PHP
    dockerfilePath: Dockerfile  # Path ke Dockerfile (opsional jika di root)
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_LEVEL
        value: error
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: APP_URL
        value: $RENDER_EXTERNAL_URL